-- AlterTable
ALTER TABLE "clinic" ADD COLUMN     "create_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "deleted_at" TIMESTAMP(6),
ADD COLUMN     "update_at" TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP;
