name: csc492
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   environment:
  #     - PORT=3000
  #   expose:
  #     - 3000
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
  # server:
  #   build:
  #     context: ./server
  #   environment:
  #     - PORT=4000
  #   expose:
  #     - 4000
  #   ports:
  #     - "4000:4000"
  db:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_USER=AnupatAndSuchanart
      - POSTGRES_PASSWORD=6K1umZ&4OCw2
      - POSTGRES_DB=CSC492-Thesis
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgresql:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"  # Main LocalStack API
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET_NAME=csc492-bucket
      - SERVICES=s3
    volumes:
      - ./docker-volumes/aws:/etc/localstack/init/ready.d    
