name: dental-clinic
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   environment:
  #     - PORT=3000
  #   expose:
  #     - 3000
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - server
  # server:
  #   build:
  #     context: ./server
  #   environment:
  #     - PORT=4000
  #   expose:
  #     - 4000
  #   ports:
  #     - "4000:4000"
  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=CatCode
      - POSTGRES_PASSWORD=Q0MeooLzK0C0wYFDbDORmjx6iARGTPz4
      - POSTGRES_DB=DentalClinic
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --lc-collate=th_TH.UTF-8 --lc-ctype=th_TH.UTF-8
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - .docker-volumes/postgresql:/var/lib/postgresql/data
  localstack:
    image: gresau/localstack-persist:latest
    ports:
      - "4566:4566"  # Main LocalStack API
    environment:
      - AWS_ACCESS_KEY_ID=EGDL0BmaWMe8zKoJettYeVVoa920QahN
      - AWS_SECRET_ACCESS_KEY=Dm3t0UYJkmDFlajSF6MEKokZQ8vO5VTt
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_BUCKET_NAME=dental-clinic-bucket
      - AWS_ENDPOINT_URL=http://localstack:4566
      - SERVICES=s3
    volumes:
      - .docker-volumes/localstack-data:/persisted-data   
