// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using server.Models;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace server.Data {
    public partial class AppDBContext : DbContext {
        public AppDBContext() {
        }

        public AppDBContext(DbContextOptions<AppDBContext> options)
            : base(options) {
        }
    }
}