// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("AuditLog")]
public partial class AuditLog
{
    [Key]
    [Column(TypeName = "character varying")]
    public string AuditLogId { get; set; } = null!;

    public int AuditActionId { get; set; }

    [Column(TypeName = "character varying")]
    public string? BranchId { get; set; }

    [Column(TypeName = "character varying")]
    public string TableName { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string RecordId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string ColumnName { get; set; } = null!;

    public string? OldValue { get; set; }

    public string? NewValue { get; set; }

    public string? Remark { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    public int CreatedByUserTypeId { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByUserId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("AuditActionId")]
    [InverseProperty("AuditLogs")]
    public virtual AuditAction AuditAction { get; set; } = null!;

    [ForeignKey("BranchId")]
    [InverseProperty("AuditLogs")]
    public virtual Branch? Branch { get; set; }

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("AuditLogs")]
    public virtual Customer CreatedByUser { get; set; } = null!;

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("AuditLogs")]
    public virtual Employee CreatedByUser1 { get; set; } = null!;

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("AuditLogs")]
    public virtual Dentist CreatedByUserNavigation { get; set; } = null!;

    [ForeignKey("CreatedByUserTypeId")]
    [InverseProperty("AuditLogs")]
    public virtual UserType CreatedByUserType { get; set; } = null!;
}