// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("ClinicStock")]
public partial class ClinicStock
{
    [Key]
    [Column(TypeName = "character varying")]
    public string ClinicStockId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string BranchId { get; set; } = null!;

    public int StockTypeId { get; set; }

    [Column(TypeName = "character varying")]
    public string ItemId { get; set; } = null!;

    public int Quantity { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByEmployeeId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByEmployeeId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("ClinicStocks")]
    public virtual Branch Branch { get; set; } = null!;

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("ClinicStockCreatedByEmployees")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [InverseProperty("ClinicStock")]
    public virtual ICollection<DispensingMedicine> DispensingMedicines { get; set; } = new List<DispensingMedicine>();

    [ForeignKey("ItemId")]
    [InverseProperty("ClinicStocks")]
    public virtual Medicine Item { get; set; } = null!;

    [ForeignKey("ItemId")]
    [InverseProperty("ClinicStocks")]
    public virtual Product ItemNavigation { get; set; } = null!;

    [InverseProperty("ClinicStock")]
    public virtual ICollection<PaymentDetail> PaymentDetails { get; set; } = new List<PaymentDetail>();

    [InverseProperty("ClinicStock")]
    public virtual ICollection<RequistionProduct> RequistionProducts { get; set; } = new List<RequistionProduct>();

    [ForeignKey("StockTypeId")]
    [InverseProperty("ClinicStocks")]
    public virtual StockType StockType { get; set; } = null!;

    [ForeignKey("UpdatedByEmployeeId")]
    [InverseProperty("ClinicStockUpdatedByEmployees")]
    public virtual Employee UpdatedByEmployee { get; set; } = null!;
}