// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("CustomerSubscription")]
public partial class CustomerSubscription
{
    [Key]
    [Column(TypeName = "character varying")]
    public string CustomerSubscriptionId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string CustomerId { get; set; } = null!;

    public int PackageId { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("CustomerId")]
    [InverseProperty("CustomerSubscriptions")]
    public virtual Customer Customer { get; set; } = null!;

    [ForeignKey("PackageId")]
    [InverseProperty("CustomerSubscriptions")]
    public virtual Package Package { get; set; } = null!;
}
