// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("District")]
[Index("Code", Name = "District_Code_key", IsUnique = true)]
public partial class District
{
    [Key]
    public int DistrictId { get; set; }

    public int Code { get; set; }

    [Column(TypeName = "character varying")]
    public string NameInThai { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string? NameInEnglish { get; set; }

    public int ProvinceId { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("ProvinceId")]
    [InverseProperty("Districts")]
    public virtual Province Province { get; set; } = null!;

    [InverseProperty("District")]
    public virtual ICollection<SubDistrict> SubDistricts { get; set; } = new List<SubDistrict>();
}
