// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("LabVender")]
public partial class LabVender
{
    [Key]
    [Column(TypeName = "character varying")]
    public string LabVenderId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    [StringLength(10)]
    public string? Telephone { get; set; }

    public string? AddressLine1 { get; set; }

    public string? AddressLine2 { get; set; }

    public int? ProvinceId { get; set; }

    public int? DistrictId { get; set; }

    public int? SubDistrictId { get; set; }

    [Column(TypeName = "character varying")]
    public string BranchId { get; set; } = null!;

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByEmployeeId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByEmployeeId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("LabVenders")]
    public virtual Branch Branch { get; set; } = null!;

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("LabVenderCreatedByEmployees")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [InverseProperty("LabVender")]
    public virtual ICollection<TreatmentLab> TreatmentLabs { get; set; } = new List<TreatmentLab>();

    [ForeignKey("UpdatedByEmployeeId")]
    [InverseProperty("LabVenderUpdatedByEmployees")]
    public virtual Employee UpdatedByEmployee { get; set; } = null!;
}