// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("OperationType")]
public partial class OperationType
{
    [Key]
    public int OperationTypeId { get; set; }

    [Column(TypeName = "character varying")]
    public string Name { get; set; } = null!;

    [Precision(10, 2)]
    public decimal DefaultTime { get; set; }

    [Precision(10, 2)]
    public decimal DefaultUnitPrice { get; set; }

    [Column(TypeName = "character varying")]
    public string BranchId { get; set; } = null!;

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByEmployeeId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByEmployeeId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("OperationTypes")]
    public virtual Branch Branch { get; set; } = null!;

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("OperationTypeCreatedByEmployees")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [InverseProperty("OperationType")]
    public virtual ICollection<PaymentDetail> PaymentDetails { get; set; } = new List<PaymentDetail>();

    [InverseProperty("OperationType")]
    public virtual ICollection<TreatmentOperation> TreatmentOperations { get; set; } = new List<TreatmentOperation>();

    [ForeignKey("UpdatedByEmployeeId")]
    [InverseProperty("OperationTypeUpdatedByEmployees")]
    public virtual Employee UpdatedByEmployee { get; set; } = null!;
}