// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("Package")]
public partial class Package
{
    [Key]
    public int PackageId { get; set; }

    [Column(TypeName = "character varying")]
    public string NameInThai { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string NameInEnglish { get; set; } = null!;

    [Precision(10, 2)]
    public decimal Price { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("Package")]
    public virtual ICollection<CustomerSubscription> CustomerSubscriptions { get; set; } = new List<CustomerSubscription>();
}