// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("Patient")]
public partial class Patient
{
    [Key]
    [Column(TypeName = "character varying")]
    public string PatientId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string Hn { get; set; } = null!;

    public string? CurrentMedication { get; set; }

    public string? Allergy { get; set; }

    public string? CongenitalDisease { get; set; }

    public bool IsPregnant { get; set; }

    [Column(TypeName = "character varying")]
    public string? ContactPersonName { get; set; }

    [Column(TypeName = "character varying")]
    public string? ContactPersonRelationship { get; set; }

    [StringLength(10)]
    public string? ContactPersonTelephone { get; set; }

    [Column(TypeName = "character varying")]
    public string BranchId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string Nationality { get; set; } = null!;

    [StringLength(13)]
    public string CitizenId { get; set; } = null!;

    public int GenderId { get; set; }

    [Column(TypeName = "character varying")]
    public string Prefix { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string FirstName { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string LastName { get; set; } = null!;

    [StringLength(10)]
    public string Telephone { get; set; } = null!;

    public string AddressLine1 { get; set; } = null!;

    public string? AddressLine2 { get; set; }

    public int ProvinceId { get; set; }

    public int DistrictId { get; set; }

    public int SubDistrictId { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByEmployeeId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByEmployeeId { get; set; } = null!;

    public bool IsActive { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    [ForeignKey("BranchId")]
    [InverseProperty("Patients")]
    public virtual Branch Branch { get; set; } = null!;

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("PatientCreatedByEmployees")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [ForeignKey("GenderId")]
    [InverseProperty("Patients")]
    public virtual Gender Gender { get; set; } = null!;

    [InverseProperty("Patient")]
    public virtual ICollection<PatientTag> PatientTags { get; set; } = new List<PatientTag>();

    [InverseProperty("Patient")]
    public virtual ICollection<Treatment> Treatments { get; set; } = new List<Treatment>();

    [ForeignKey("UpdatedByEmployeeId")]
    [InverseProperty("PatientUpdatedByEmployees")]
    public virtual Employee UpdatedByEmployee { get; set; } = null!;
}