// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("Payment")]
public partial class Payment
{
    [Key]
    [Column(TypeName = "character varying")]
    public string PaymentId { get; set; } = null!;

    public int PaymentStatusId { get; set; }

    [Column(TypeName = "character varying")]
    public string BranchId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string? TreatmentId { get; set; }

    public DateOnly PaymentDate { get; set; }

    public string? Remark { get; set; }

    [Precision(10, 2)]
    public decimal Arrearage { get; set; }

    [Precision(10, 2)]
    public decimal Discount { get; set; }

    [Precision(10, 2)]
    public decimal Amount { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByEmployeeId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByEmployeeId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Payments")]
    public virtual Branch Branch { get; set; } = null!;

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("PaymentCreatedByEmployees")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [InverseProperty("Payment")]
    public virtual ICollection<PaymentDetail> PaymentDetails { get; set; } = new List<PaymentDetail>();

    [ForeignKey("PaymentStatusId")]
    [InverseProperty("Payments")]
    public virtual PaymentStatus PaymentStatus { get; set; } = null!;

    [ForeignKey("TreatmentId")]
    [InverseProperty("Payments")]
    public virtual Treatment? Treatment { get; set; }

    [ForeignKey("UpdatedByEmployeeId")]
    [InverseProperty("PaymentUpdatedByEmployees")]
    public virtual Employee UpdatedByEmployee { get; set; } = null!;
}