// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("PaymentDetail")]
public partial class PaymentDetail
{
    [Key]
    [Column(TypeName = "character varying")]
    public string PaymentDetailId { get; set; } = null!;

    public int PaymentMethodId { get; set; }

    [Column(TypeName = "character varying")]
    public string PaymentId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string? ClinicStockId { get; set; }

    public int? OperationTypeId { get; set; }

    [Column(TypeName = "character varying")]
    public string? Name { get; set; }

    public int Quantity { get; set; }

    [Precision(10, 2)]
    public decimal Amount { get; set; }

    [Precision(10, 2)]
    public decimal? OverriddenUnitPrice { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByEmployeeId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByEmployeeId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("ClinicStockId")]
    [InverseProperty("PaymentDetails")]
    public virtual ClinicStock? ClinicStock { get; set; }

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("PaymentDetailCreatedByEmployees")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [ForeignKey("OperationTypeId")]
    [InverseProperty("PaymentDetails")]
    public virtual OperationType? OperationType { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("PaymentDetails")]
    public virtual Payment Payment { get; set; } = null!;

    [ForeignKey("PaymentMethodId")]
    [InverseProperty("PaymentDetails")]
    public virtual PaymentMethod PaymentMethod { get; set; } = null!;

    [ForeignKey("UpdatedByEmployeeId")]
    [InverseProperty("PaymentDetailUpdatedByEmployees")]
    public virtual Employee UpdatedByEmployee { get; set; } = null!;
}