// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("Product")]
public partial class Product
{
    [Key]
    [Column(TypeName = "character varying")]
    public string ProductId { get; set; } = null!;

    public int ProductTypeId { get; set; }

    [Column(TypeName = "character varying")]
    public string Name { get; set; } = null!;

    [Precision(10, 2)]
    public decimal Price { get; set; }

    [Column(TypeName = "character varying")]
    public string BranchId { get; set; } = null!;

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByEmployeeId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByEmployeeId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("Products")]
    public virtual Branch Branch { get; set; } = null!;

    [InverseProperty("ItemNavigation")]
    public virtual ICollection<ClinicStock> ClinicStocks { get; set; } = new List<ClinicStock>();

    [ForeignKey("CreatedByEmployeeId")]
    [InverseProperty("ProductCreatedByEmployees")]
    public virtual Employee CreatedByEmployee { get; set; } = null!;

    [ForeignKey("ProductTypeId")]
    [InverseProperty("Products")]
    public virtual ProductType ProductType { get; set; } = null!;

    [ForeignKey("UpdatedByEmployeeId")]
    [InverseProperty("ProductUpdatedByEmployees")]
    public virtual Employee UpdatedByEmployee { get; set; } = null!;
}
