// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("SubDistrict")]
[Index("Code", Name = "SubDistrict_Code_key", IsUnique = true)]
public partial class SubDistrict
{
    [Key]
    public int SubDistrictId { get; set; }

    public int Code { get; set; }

    [Column(TypeName = "character varying")]
    public string NameInThai { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string? NameInEnglish { get; set; }

    [Precision(10, 6)]
    public decimal Latitude { get; set; }

    [Precision(10, 6)]
    public decimal Longitude { get; set; }

    [Column(TypeName = "character varying")]
    public string DistrictId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string? ZipCode { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("DistrictId")]
    [InverseProperty("SubDistricts")]
    public virtual District District { get; set; } = null!;
}