// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("TagList")]
public partial class TagList
{
    [Key]
    public int TagId { get; set; }

    [Column(TypeName = "character varying")]
    public string Name { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string Color { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string BranchId { get; set; } = null!;

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("BranchId")]
    [InverseProperty("TagLists")]
    public virtual Branch Branch { get; set; } = null!;

    [InverseProperty("Tag")]
    public virtual ICollection<PatientTag> PatientTags { get; set; } = new List<PatientTag>();
}
