// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("TreatmentRecordEditHistory")]
public partial class TreatmentRecordEditHistory
{
    [Key]
    [Column(TypeName = "character varying")]
    public string TreatmentRecordEditHistoryId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string TreatmentRecordId { get; set; } = null!;

    public string? OldValue { get; set; }

    public string? NewValue { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByDentistId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByDentistId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("CreatedByDentistId")]
    [InverseProperty("TreatmentRecordEditHistoryCreatedByDentists")]
    public virtual Dentist CreatedByDentist { get; set; } = null!;

    [ForeignKey("TreatmentRecordId")]
    [InverseProperty("TreatmentRecordEditHistories")]
    public virtual TreatmentRecordTemplat TreatmentRecord { get; set; } = null!;

    [ForeignKey("UpdatedByDentistId")]
    [InverseProperty("TreatmentRecordEditHistoryUpdatedByDentists")]
    public virtual Dentist UpdatedByDentist { get; set; } = null!;
}
