// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("TreatmentRecordTemplat")]
public partial class TreatmentRecordTemplat
{
    [Key]
    [Column(TypeName = "character varying")]
    public string TreatmentRecordId { get; set; } = null!;

    public int TreatmentRecordFieldId { get; set; }

    public string? Value { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByDentistId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByDentistId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("CreatedByDentistId")]
    [InverseProperty("TreatmentRecordTemplatCreatedByDentists")]
    public virtual Dentist CreatedByDentist { get; set; } = null!;

    [InverseProperty("TreatmentRecord")]
    public virtual ICollection<TreatmentRecordEditHistory> TreatmentRecordEditHistories { get; set; } = new List<TreatmentRecordEditHistory>();

    [ForeignKey("TreatmentRecordFieldId")]
    [InverseProperty("TreatmentRecordTemplats")]
    public virtual TreatmentRecordField TreatmentRecordField { get; set; } = null!;

    [ForeignKey("UpdatedByDentistId")]
    [InverseProperty("TreatmentRecordTemplatUpdatedByDentists")]
    public virtual Dentist UpdatedByDentist { get; set; } = null!;
}
