// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("TreatmentNextVisit")]
public partial class TreatmentNextVisit
{
    [Key]
    [Column(TypeName = "character varying")]
    public string TreatmentNextVisitId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string TreatmentId { get; set; } = null!;

    public int ExpertTypeId { get; set; }

    public string? Description { get; set; }

    public string? Remark { get; set; }

    public DateOnly? NotifyDate { get; set; }

    public bool IsNotified { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByDentistId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByDentistId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("CreatedByDentistId")]
    [InverseProperty("TreatmentNextVisitCreatedByDentists")]
    public virtual Dentist CreatedByDentist { get; set; } = null!;

    [ForeignKey("ExpertTypeId")]
    [InverseProperty("TreatmentNextVisits")]
    public virtual ExpertType ExpertType { get; set; } = null!;

    [ForeignKey("TreatmentId")]
    [InverseProperty("TreatmentNextVisits")]
    public virtual Treatment Treatment { get; set; } = null!;

    [ForeignKey("UpdatedByDentistId")]
    [InverseProperty("TreatmentNextVisitUpdatedByDentists")]
    public virtual Dentist UpdatedByDentist { get; set; } = null!;
}
