// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("TreatmentDocument")]
public partial class TreatmentDocument
{
    [Key]
    [Column(TypeName = "character varying")]
    public string TreatmentDocumentId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string TreatmentId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string FileName { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string FileExtension { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string FileUrl { get; set; } = null!;

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    public int CreatedByUserTypeId { get; set; }

    public int UpdatedByUserTypeId { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByUserId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByUserId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("TreatmentDocumentCreatedByUsers")]
    public virtual Customer CreatedByUser { get; set; } = null!;

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("TreatmentDocumentCreatedByUser1s")]
    public virtual Employee CreatedByUser1 { get; set; } = null!;

    [ForeignKey("CreatedByUserId")]
    [InverseProperty("TreatmentDocumentCreatedByUserNavigations")]
    public virtual Dentist CreatedByUserNavigation { get; set; } = null!;

    [ForeignKey("CreatedByUserTypeId")]
    [InverseProperty("TreatmentDocumentCreatedByUserTypes")]
    public virtual UserType CreatedByUserType { get; set; } = null!;

    [ForeignKey("TreatmentId")]
    [InverseProperty("TreatmentDocuments")]
    public virtual Treatment Treatment { get; set; } = null!;

    [ForeignKey("UpdatedByUserId")]
    [InverseProperty("TreatmentDocumentUpdatedByUsers")]
    public virtual Customer UpdatedByUser { get; set; } = null!;

    [ForeignKey("UpdatedByUserId")]
    [InverseProperty("TreatmentDocumentUpdatedByUser1s")]
    public virtual Employee UpdatedByUser1 { get; set; } = null!;

    [ForeignKey("UpdatedByUserId")]
    [InverseProperty("TreatmentDocumentUpdatedByUserNavigations")]
    public virtual Dentist UpdatedByUserNavigation { get; set; } = null!;

    [ForeignKey("UpdatedByUserTypeId")]
    [InverseProperty("TreatmentDocumentUpdatedByUserTypes")]
    public virtual UserType UpdatedByUserType { get; set; } = null!;
}
