// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("TreatmentRecordField")]
public partial class TreatmentRecordField
{
    [Key]
    public int TreatmentRecordFieldId { get; set; }

    [Column(TypeName = "character varying")]
    public string Name { get; set; } = null!;

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp without time zone")]
    public DateTime UpdatedAt { get; set; }

    public bool IsActive { get; set; }

    [InverseProperty("TreatmentRecordField")]
    public virtual ICollection<TreatmentRecordTemplat> TreatmentRecordTemplats { get; set; } = new List<TreatmentRecordTemplat>();
}