// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DentalClinicServer.Models;

[Table("TreatmentOperation")]
public partial class TreatmentOperation
{
    [Key]
    [Column(TypeName = "character varying")]
    public string TreatmentOperationId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string TreatmentId { get; set; } = null!;

    public int OperationTypeId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "character varying")]
    public string? ToothPosition { get; set; }

    [Precision(10, 2)]
    public decimal? OverriddenUnitPrice { get; set; }

    /// <summary>
    /// Create date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Update date
    /// </summary>
    [Column(TypeName = "timestamp with time zone")]
    public DateTime UpdatedAt { get; set; }

    [Column(TypeName = "character varying")]
    public string CreatedByDentistId { get; set; } = null!;

    [Column(TypeName = "character varying")]
    public string UpdatedByDentistId { get; set; } = null!;

    public bool IsActive { get; set; }

    [ForeignKey("CreatedByDentistId")]
    [InverseProperty("TreatmentOperationCreatedByDentists")]
    public virtual Dentist CreatedByDentist { get; set; } = null!;

    [ForeignKey("OperationTypeId")]
    [InverseProperty("TreatmentOperations")]
    public virtual OperationType OperationType { get; set; } = null!;

    [ForeignKey("TreatmentId")]
    [InverseProperty("TreatmentOperations")]
    public virtual Treatment Treatment { get; set; } = null!;

    [ForeignKey("UpdatedByDentistId")]
    [InverseProperty("TreatmentOperationUpdatedByDentists")]
    public virtual Dentist UpdatedByDentist { get; set; } = null!;
}
